name: Publish

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Install tools
      run: |
        cargo install cargo-release
        cargo install cargo-deb
        cargo install git-cliff

    - name: Setup Cargo authentication
      run: |
        mkdir -p ~/.cargo
        echo "[registry]" > ~/.cargo/credentials
        echo "token = \"${{ secrets.CARGO_REGISTRY_TOKEN }}\"" >> ~/.cargo/credentials
        chmod 0600 ~/.cargo/credentials

    - name: Release
      run: |
        cargo release ${{ github.event.inputs.level }} --execute --no-confirm

    - name: Generate Release Notes
      run: |
        git cliff --latest --output CHANGELOG.md
        
    - name: Build Debian package
      run: |
        cargo deb

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/debian/*.deb
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}