name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release
    
    - name: Run tests
      run: cargo test --verbose

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Create Debian package
      run: cargo deb

    - name: Get Version
      id: get_version
      run: echo "version=$(cargo metadata --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

    - name: Check if tag exists
      id: tag_check
      run: |
        if git ls-remote --exit-code --tags origin "refs/tags/v${{ steps.get_version.outputs.version }}"; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main' && steps.tag_check.outputs.exists == 'false'
      with:
        files: target/debian/*.deb
        tag_name: v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
